project:
  type: website
  output-dir: docs

book:
  title: "diary"
  author: "Jane Doe"
  date: "13/02/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

